/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void mainControlPanel_Click1(GPanel source, GEvent event) { //_CODE_:mainControlPanel:436933:
  println("panel1 - GPanel >> GEvent." + event + " @ " + millis());
} //_CODE_:mainControlPanel:436933:

public void dropList1_click1(GDropList source, GEvent event) { //_CODE_:dropList1:285537:
  println("dropList1 - GDropList >> GEvent." + event + " @ " + millis());
} //_CODE_:dropList1:285537:

public void slider_yRotation_change1(GSlider source, GEvent event) { //_CODE_:slider_yRotation:486820:
  println("slider_yRotation - GSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:slider_yRotation:486820:

public void slider2d1_change1(GSlider2D source, GEvent event) { //_CODE_:slider2d1:412024:
  println("slider2d1 - GSlider2D >> GEvent." + event + " @ " + millis());
} //_CODE_:slider2d1:412024:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  mainControlPanel = new GPanel(this, 16, 944, 800, 240, "Grid Controls");
  mainControlPanel.setCollapsible(false);
  mainControlPanel.setText("Grid Controls");
  mainControlPanel.setOpaque(true);
  mainControlPanel.addEventHandler(this, "mainControlPanel_Click1");
  dropList1 = new GDropList(this, 688, 32, 90, 48, 2, 10);
  dropList1.setItems(loadStrings("list_285537"), 0);
  dropList1.addEventHandler(this, "dropList1_click1");
  slider_yRotation = new GSlider(this, 16, 32, 192, 16, 10.0);
  slider_yRotation.setLimits(0.5, 0.0, 1.0);
  slider_yRotation.setStickToTicks(true);
  slider_yRotation.setNumberFormat(G4P.DECIMAL, 1);
  slider_yRotation.setOpaque(false);
  slider_yRotation.addEventHandler(this, "slider_yRotation_change1");
  slider2d1 = new GSlider2D(this, 480, 32, 192, 192);
  slider2d1.setLimitsX(0.5, 0.0, 1.0);
  slider2d1.setLimitsY(0.5, 0.0, 1.0);
  slider2d1.setNumberFormat(G4P.DECIMAL, 2);
  slider2d1.setOpaque(true);
  slider2d1.addEventHandler(this, "slider2d1_change1");
  mainControlPanel.addControl(dropList1);
  mainControlPanel.addControl(slider_yRotation);
  mainControlPanel.addControl(slider2d1);
}

// Variable declarations 
// autogenerated do not edit
GPanel mainControlPanel; 
GDropList dropList1; 
GSlider slider_yRotation; 
GSlider2D slider2d1; 
